### ISSUE TITLE
Unable to expose 10000 port outside

### ISSUE THREAD

**Issue by harmandeeps** [kgyrtkirk/hive-dev-box#4]
I am able to successfully start hive container. But, I want to expose 10000 outside the container. I tried many things I found on the internet but nothing worked. Please let me know if there is any way?

Thank you.

**Comment by kgyrtkirk** [comment]
I tend to use it internally; and I tend to try to move everything inside - but of course this might not be possible all the time :D

* you should be able to the HS2 thru the container's ip (`ip a` or `ifconfig` in the container)
for more approaches:
https://stackoverflow.com/questions/19897743/exposing-a-port-on-a-live-docker-container
* if the previous doesn't work: you could add a port forward by changing `run.bash`; to have line like:
```
RUN_OPTS+=" -p10000:10000"
```
but... if you expose 10000 externally (and its built into the launch script) you will not be able to launch the second container

**Comment by harmandeeps** [comment]
Thanks for the quick response, running the service internally worked fine :)
